stages:
  split:
    cmd: python3 src/data/split.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  
  normalize:
    cmd: python src/data/normalize.py
    deps:
      - src/data/normalize.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
  
  gridsearch:
    cmd: python src/data/modeling.py
    deps:
      - src/data/modeling.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - params.yaml
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/data/train.py
    deps:
      - src/data/train.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    outs:
      - models/trained_model.pkl

  evaluate:
    cmd: python src/data/evaluation.py
    deps:
      - src/data/evaluation.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/trained_model.pkl
    metrics:
      - metrics/scores.json:
          cache: false